apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ${{ values.component_id }}-pipeline
spec:
  workspaces:
  - name: maven-repo
  - name: maven-settings

  params:
    - default: ./src/main/docker/Dockerfile
      name: dockerfilePath
      type: string
      description: Path containing the Dockerfile for the final image
    - default: https://github.com/contract-first-idp/${{ values.component_id }}
      name: git-url
      type: string
      description: "Upstream Source Repository Url"
    - default: main
      name: git-revision
      type: string
      description: "Upstream source code revision to pull"
    - default: image-registry.openshift-image-registry.svc:5000/${{values.application.split("/")[1]}}-dev/${{ values.component_id }}:latest
      name: image-name
      type: string
      description: "Target OCI image name"

  tasks:
  - name: clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.git-revision)
    workspaces:
    - name: output
      workspace: maven-repo

  - name: build
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter: ["clone"]
    params:
    - name: GOALS
      value: ["compile"]
    workspaces:
    - name: source
      workspace: maven-repo
    - name: maven-settings
      workspace: maven-settings

  - name: package
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter: ["build"]
    params:
    - name: GOALS
      value: ["package"]
    workspaces:
    - name: source
      workspace: maven-repo
    - name: maven-settings
      workspace: maven-settings

  - name: build-container-image
    runAfter: ["package"]
    taskRef:
      name: buildah
      kind: ClusterTask
    workspaces:
    - name: source
      workspace: maven-repo
    params:
    - name: IMAGE
      value: $(params.image-name)
    - name: DOCKERFILE
      value: $(params.dockerfilePath)
