apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ${{ values.api_id }}-api-pipeline
spec:
  description: | 
    This pipeline runs a Spectral linter against an API specification and publishes to Microcks
  params:
  - default: https://github.com/contract-first-idp/${{ values.api_id }}
    name: repo-url
    type: string
  - default: master
    name: gitRevision
    type: string
  - default: "stoplight/spectral:6.11.1"
    name: spectral-image
    type: string
  - default: https://raw.githubusercontent.com/contract-first-idp/spectral-rules/main/ruleset.yaml
    name: rules-path
    type: string
  - default: ./specification.yaml
    name: api-path
    type: string
  workspaces:
  - name: shared-data
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: "$(params.gitRevision)"
    workspaces:
    - name: output
      workspace: shared-data
  - name: run-spectral
    runAfter: ["fetch-source"]
    taskRef:
      name: spectral-quality-gate
      kind: ClusterTask
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: RULES_PATH
      value: $(params.rules-path)
    - name: API_PATH
      value: $(params.api-path)
    - name: IMAGE
      value: $(params.spectral-image)
  - name: run-microcks-import
    runAfter: ["run-spectral"]
    taskRef:
      name: microcks-import
      kind: ClusterTask
    workspaces:
    - name: data
      workspace: shared-data
