apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.application_id}}-root-application
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/contract-first-idp/${{values.application_id}}-gitops.git
    path: "."
    directory:
      include: "*.yaml"
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 0
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m