apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.api_id | dump}}
  title: ${{values.api_id | dump}}
  description: ${{values.description | dump}}
  annotations:
    backstage.io/spectral-ruleset-url: https://raw.githubusercontent.com/contract-first-idp/api-spec-prototype/main/.spectral.yaml
spec:
  type: openapi
  system: ${{values.application}}
  owner: ${{values.owner | dump}}
  lifecycle: experimental
  definition:
    $openapi: ${{ values.destination }}/blob/master/specification.yaml