apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: api-specification-template
  title: OpenAPI Specification
  description: Create an OpenAPI specification
spec:
  owner: service@example.com
  type: api

  parameters:
    - title: API server parameters
      required:
        - api_id
        - owner
        - application
        - description
      properties:
        api_id:
          title: Name
          type: string
          description: Unique name of the API
        description:
          title: Description
          type: string
          description: API description
        owner:
          title: Owner
          type: string
          description: Owner of the API
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - Group
        application:
          title: System
          type: string
          description: System to which this API belongs
          ui:field: OwnedEntityPicker
          ui:options:
            allowedKinds:
            - System
        mock_provider_url:
          title: Mock Provider URL
          type: string
          description: Microcks Host
          default: https://microcks-microcks.apps.cluster-example.com
        service_registry_provider_url:
          title: Service Registry Provider URL
          type: string
          description: Apicurio Registry Host
          default: https://registry-apicurio-registry.apps.cluster-example.com
        group_id:
          title: Apicurio Registry Group ID
          type: string
          default: com.redhat

  steps:
    - id: template
      name: render API specification
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender: []
        values:
          api_id: ${{ parameters.api_id }}
          description: ${{ parameters.description }}
          mock_provider_url: ${{ parameters.mock_provider_url }}
          owner: ${{ parameters.owner }}
          destination: https://github.com/contract-first-idp/${{ parameters.application.split("/")[1] }}-${{ parameters.api_id }}-api
          application: ${{ parameters.application }}
          service_registry_provider_url: ${{ parameters.service_registry_provider_url }}
          group_id: ${{ parameters.group_id }}

    - id: publish
      name: publish API specification repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.api_id }}
        repoUrl: github.com?repo=${{ parameters.application.split("/")[1] }}-${{ parameters.api_id }}-api&owner=contract-first-idp
        repoVisibility: public
        defaultBranch: main
        deleteBranchOnMerge: true
        protectDefaultBranch: false

    - id: template-system-pull-request
      name: render system pull request
      action: fetch:template
      input:
        url: ./system
        copyWithoutRender: []
        values:
          api_id: ${{ parameters.api_id }}
          application: ${{ parameters.application }}
        targetPath: ./system-gitops

    - id: pull-request-to-system
      name: open system pull request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=${{ parameters.application.split("/")[1] }}-system&owner=contract-first-idp
        branchName: ${{ parameters.api_id }}-api
        title: add ${{ parameters.api_id }} API
        description: add ${{ parameters.api_id}} API
        sourcePath: ./system-gitops
