apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: api-specification-template
  title: OpenAPI Specification
  description: Create an OpenAPI specification
spec:
  owner: service@example.com
  type: api

  parameters:
    - title: API server parameters
      required:
        - api_id
        - owner
        - application
        - description
      properties:
        api_id:
          title: Name
          type: string
          description: Unique name of the API
        description:
          title: Description
          type: string
          description: API description
        owner:
          title: Owner
          type: string
          description: Owner of the API
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - Group
        application:
          title: System
          type: string
          description: System to which this API belongs
          ui:field: OwnedEntityPicker
          ui:options:
            allowedKinds:
            - System
        mock_provider_url:
          title: Mock Provider URL
          type: string
          description: Microcks Host
          default: https://microcks-microcks.apps.cluster-n7s8n.dynamic.redhatworkshops.io

  steps:
    - id: template
      name: Render API Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender: []
        values:
          api_id: ${{ parameters.api_id }}
          description: ${{ parameters.description }}
          mock_provider_url: ${{ parameters.mock_provider_url }}
          owner: ${{ parameters.owner }}
          destination: https://github.com/contract-first-idp/${{ parameters.api_id }}
          application: ${{ parameters.application }}

    - id: publish
      name: Publish API Repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.api_id }}
        repoUrl: github.com?repo=${{ parameters.api_id }}&owner=contract-first-idp
        repoVisibility: public
        deleteBranchOnMerge: true
        #access: contract-first-idp/${{ parameters.owner }}
        protectDefaultBranch: false

    - id: template-tenant-gitops 
      name: Render GitOps Template
      action: fetch:template
      input:
        url: ./app-gitops
        copyWithoutRender: []
        values:
          api_id: ${{ parameters.api_id }}
          application: ${{ parameters.application }}
        targetPath: ./tenant-gitops

    - id: pull-request
      name: Open PR to System
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=${{ parameters.application.split("/")[1] }}-gitops&owner=contract-first-idp
        branchName: ${{ parameters.api_id }}
        title: argocd apps for ${{ parameters.api_id }}
        description: argocd apps ${{ parameters.api_id}}
        sourcePath: ./tenant-gitops
