schemaVersion: 2.2.0
metadata:
  name: ${{values.component_id}}
  version: 0.0.1
  displayName: CSB Java ubi8
  description: CSB and ubi8 image
  generateName: ${{values.component_id}}
  icon: >-
    https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/java-maven.jpg
  tags:
    - Java
    - Spring
    - Camel
  projectType: spring
  language: java
attributes:
  controller.devfile.io/storage-type: per-workspace
components:
  - name: development-tooling
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:latest
      env:
        - name: MAVEN_OPTS
          value: "-Dmaven.repo.local=/home/user/.m2/repository"
      memoryLimit: 5Gi
      cpuLimit: 2500m
      sourceMapping: $PROJECT_SOURCE
      mountSources: true
      volumeMounts:
        - name: m2
          path: /home/user/.m2
      endpoints:
        - name: http-8778
          targetPort: 8778
        - name: devtools
          targetPort: 8000
        - name: http
          targetPort: 8080
          exposure: public
          secure: false
          protocol: http
        - name: management
          targetPort: 8081
          secure: false
          protocol: http
        - name: http-8443
          targetPort: 8443
  - name: m2
    volume:
      size: 1G
commands:
  - id: package
    exec:
      label: "1. Package the application"
      component: development-tooling
      commandLine: "./mvnw package"
      group:
        kind: build
        isDefault: true
  - id: start-dev
    exec:
      label: "2. Run Spring Boot application"
      component: development-tooling
      commandLine: "./mvnw compile spring-boot:run"
      group:
        kind: run
        isDefault: true
  - id: fix-java-version
    exec:
      component: development-tooling
      commandLine: 'rm -rf ${HOME}/.java/current/* && ln -s /usr/lib/jvm/java-17-openjdk/* ${HOME}/.java/current'
events:
  postStart:
    - fix-java-version